// src/lib/pre-registration/sheet-columns.ts
// Canonical column order for the pre-registration Google Sheet.
// scripts/apps-script/Code.gs MUST declare the same SHEET_COLUMNS array, in the same
// order — the build test in tests/pre-registration-form.test.mjs asserts they match.

export const PRE_REGISTRATION_SHEET_COLUMNS = [
  "Submitted At",
  "Submission ID",
  "Language",
  "Competition Slug",
  "Competition Name",
  "Project Name",
  "Project Introduction",
  "Competition Field",
  "Company Headquarters",
  "Company Location",
  "Company Full Name",
  "Office Address",
  "Applicant Name",
  "Gender",
  "Date Of Birth",
  "Nationality",
  "Graduation Institution",
  "Highest Degree",
  "WeChat Or WhatsApp",
  "LinkedIn",
  "Email",
  "Elevator Pitch",
  "Project Overview",
  "Product Features",
  "Business Model",
  "Team Introduction",
  "Investment Value",
  "Funding Amount Requested",
  "Expected Benefits",
  "Hear About",
  "Expansion Plan",
  "Incorporation Timeline",
  "Pitch Deck Link",
  "Supplementary Links",
  "User Agent",
  "Referrer",
  "Raw JSON",
] as const;
